version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - planetx
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    networks:
      - planetx
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - planetx
    depends_on:
      - postgres
      - redis
    tty: true
    develop:
      watch:
        - action: sync+restart
          path: ./prisma
          target: /app/prisma
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        - action: sync
          path: ./node_modules
          target: /app/node_modules
        

volumes:
  postgres_data:
  redis_data:

networks:
  planetx:
    name: planetx