version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - planetx
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - planetx
    depends_on:
      - postgres
    tty: true
    develop:
      watch:
        - action: sync+restart
          path: ./prisma
          target: /app/prisma
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        

volumes:
  postgres_data:

networks:
  planetx:
    name: planetx