import { z } from "zod";

export const GymCreateSchema = z.object({
    gymName: z.string().min(1, "Gym name is required"),
    locationLatitude: z.number(),
    locationLongitude: z.number(),
    yearOfGym: z.number().int().gte(1900).lte(new Date().getFullYear()),
    description: z.string().min(1, "Description is required"),
    photos: z.array(z.string()).optional().default([]),
    videos: z.array(z.string()).optional().default([]),
    lockerFacility: z.boolean(),
    timing: z.any(),
    categories: z.array(z.string()).min(1, "At least one category is required"),
    rateCard: z.string().optional(),
    website: z.string().url("Invalid URL").optional(),
    services: z.array(z.string()).min(1, "At least one service is required"),
    benefits: z.array(z.string()).optional().default([]),
    pricing: z.any(),
    amenities: z.array(z.string()).optional().default([]),
    availableSports: z.array(z.string()).optional().default([]),
    strengthEquipments: z.array(z.string()).optional().default([]),
    cardioEquipments: z.array(z.string()).optional().default([]),
    rules: z.array(z.string()).optional().default([]),
    gender: z.enum(["Male", "Female", "Unisex"]),
    counsellingServices: z.any(),
    socialMediaLinks: z.any(),
});

export const GymUpdateSchema = z.object({
    gymName: z.string().min(1).optional(),
    locationLatitude: z.number().optional(),
    locationLongitude: z.number().optional(),
    yearOfGym: z.number().int().gte(1900).lte(new Date().getFullYear()).optional(),
    description: z.string().optional(),
    photos: z.array(z.string()).optional(),
    videos: z.array(z.string()).optional(),
    lockerFacility: z.boolean().optional(),
    timing: z.any().optional(),
    categories: z.array(z.string()).optional(),
    rateCard: z.string().optional().nullable(),
    website: z.string().url("Invalid URL").optional().nullable(),
    services: z.array(z.string()).optional(),
    benefits: z.array(z.string()).optional(),
    pricing: z.any().optional(),
    amenities: z.array(z.string()).optional(),
    availableSports: z.array(z.string()).optional(),
    strengthEquipments: z.array(z.string()).optional(),
    cardioEquipments: z.array(z.string()).optional(),
    rules: z.array(z.string()).optional(),
    gender: z.enum(["Male", "Female", "Unisex"]).optional(),
    counsellingServices: z.any().optional(),
    socialMediaLinks: z.any().optional()
});
