-- CreateTable
CREATE TABLE "Gym" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "gymName" TEXT NOT NULL,
    "locationLatitude" DOUBLE PRECISION NOT NULL,
    "locationLongitude" DOUBLE PRECISION NOT NULL,
    "yearOfGym" INTEGER NOT NULL,
    "description" TEXT NOT NULL,
    "photos" TEXT[],
    "videos" TEXT[],
    "lockerFacility" BOOLEAN NOT NULL,
    "timing" JSONB NOT NULL,
    "categories" TEXT[],
    "rateCard" TEXT,
    "website" TEXT,
    "services" TEXT[],
    "benefits" TEXT[],
    "pricing" JSONB NOT NULL,
    "amenities" TEXT[],
    "availableSports" TEXT[],
    "strengthEquipments" TEXT[],
    "cardioEquipments" TEXT[],
    "rules" TEXT[],
    "gender" TEXT NOT NULL,
    "counsellingServices" JSONB NOT NULL,
    "socialMediaLinks" JSONB NOT NULL,

    CONSTRAINT "Gym_pkey" PRIMARY KEY ("id")
);
